version: "3"
services:
  app:
    build: ./app
    container_name: app
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
  db:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/bd_init:/docker-entrypoint-initdb.d/:ro
