USE glo_2005;
insert into product_types (id, name) values 
(1, 'Furniture'),
(2, 'Clothing'),
(3, 'Pet Supplies'),
(4, 'Footwear'),
(5, 'Pens & Stationery'),
(6, 'Bags & Wallets & Belts'),
(7, 'Home Decor & Festive Needs'),
(8, 'Automotive'),
(9, 'Tools & Hardware'),
(10, 'Sports & Fitness'),
(11, 'Home Furnishing'),
(12, 'Baby Care'),
(13, 'Mobiles & Accessories'),
(14, 'Toys & School Supplies'),
(15, 'Jewellery'),
(16, 'Kitchen & Dining'),
(17, 'Beauty and Personal Care'),
(18, 'Home & Kitchen'),
(19, 'Computers'),
(20, 'Watches'),
(21, 'Cameras & Accessories'),
(22, 'Health & Personal Care Appliances'),
(23, 'Gaming'),
(24, 'Home Improvement'),
(25, 'Automation & Robotics'),
(26, 'Sunglasses'),
(27, 'Home Entertainment'),
(28, 'Wearable Smart Devices'),
(29, 'Eyewear'),
(30, 'eBooks'),
(31, 'Household Supplies');
